version: '3'
services:
  database:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 5101:3306
    cap_add:
      - SYS_NICE
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - nginx-proxy
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'

  directus:
    container_name: directus
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - ./uploads:/directus/uploads
      # Make sure to also mount the volume when using SQLite
      # - ./database:/directus/database
      # If you want to load extensions from the host
      - ./extensions:/directus/extensions
    networks:
      - nginx-proxy
    depends_on:
      - database
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'mysql'
      DB_HOST: 'database'
      DB_PORT: '3306'
      DB_DATABASE: '${MYSQL_DATABASE}'
      DB_USER: 'root'
      DB_PASSWORD: '${MYSQL_ROOT_PASSWORD}'

      ADMIN_EMAIL: '${DIRECTUS_ADMIN_EMAIL}'
      ADMIN_PASSWORD: '${DIRECTUS_ADMIN_PASSWORD}'

      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      PUBLIC_URL: 'https://admin.olivetced.fr'

networks:
  default:
    name: nginx-proxy
    external: true

volumes:
  mysql-data: