version: '3.8'
services:
  olivetced-database:
    container_name: olivetced-database
    restart: unless-stopped
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 5101:${MYSQL_PORT}
    cap_add:
      - SYS_NICE
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-ppass"]
      interval: 5s
      timeout: 5s
      retries: 20

  olivetced-directus:
    container_name: olivetced-directus
    restart: unless-stopped
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - ./uploads:/directus/uploads
      # Make sure to also mount the volume when using SQLite
      # - ./database:/directus/database
      # If you want to load extensions from the host
      - ./extensions:/directus/extensions
    networks:
      - default
    depends_on:
      olivetced-database:
        condition: service_healthy
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'mysql'
      DB_HOST: '${MYSQL_HOST}'
      DB_PORT: '${MYSQL_PORT}'
      DB_DATABASE: '${MYSQL_DATABASE}'
      DB_USER: 'root'
      DB_PASSWORD: '${MYSQL_ROOT_PASSWORD}'

      ADMIN_EMAIL: '${DIRECTUS_ADMIN_EMAIL}'
      ADMIN_PASSWORD: '${DIRECTUS_ADMIN_PASSWORD}'

      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      PUBLIC_URL: 'https://admin.olivetced.fr'

networks:
  default:
    name: nginx-proxy
    external: true

volumes:
  mysql-data: